#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 01, 2020 08:19:27 AM PST  platform: Windows NT

import mysql.connector
import RestaurantManagement

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import ShowTable_support



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = ShowTable(root)
    ShowTable_support.init(root, top)
    root.mainloop()


w = None


def create_ShowTable(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = ShowTable(w)
    ShowTable_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_ShowTable():
    global w
    w.destroy()
    w = None


class ShowTable:
    def describeTable(self):
        self.mycursor.execute("desc users")
        result = self.mycursor.fetchall()
        j = 0
        for i in result:
            self.Listbox1.insert(j, i)
            j = j + 1

    def ExecuteQuery(self):
        try:
            self.mycursor.execute(
                "SELECT table_name, table_rows FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '{}'".format(RestaurantManagement.databasename))
            result = self.mycursor.fetchall()
            j = 0
            for i in result:

                self.Listbox1.insert(j, "***************")
                j = j + 1
                self.Listbox1.insert(j, "{} ".format(i[0]))
                query = "desc {}".format(i[0])
                self.mycursor.execute(query)
                queryResult = self.mycursor.fetchall()

                j = j + 1
                self.Listbox1.insert(j, "1)Field   2)Type  3)Null   4)Key  5)Default 6)Extra")

                for x in queryResult:
                    j = j + 1
                    self.Listbox1.insert((j),
                                         "1){}   2){}   3){}    4){}   5){}  6){}".format(x[0], x[1], x[2], x[3], x[4],
                                                                                          x[5]))
                    j = j + 1
        except Exception:
            print("hata")

    def __init__(self, top=None):
        with open('database.config', 'r+') as reader:
            line = reader.readline()
            databasename = line.split("\n")[0]
            line = reader.readline()
            username = line.split("\n")[0]
            line = reader.readline()
            password = line.split("\n")[0]
            reader.close()
        try:
            self.cnx = mysql.connector.connect(user=username, password=password,
                                               host="localhost", database=databasename)
            self.mycursor = self.cnx.cursor()
        except Exception:
            print(Exception)
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("900x500")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("Show Tables")
        top.configure(background="#d9d9d9")

        self.Listbox1 = tk.Listbox(top)
        self.scroll = tk.Scrollbar(root, command=self.Listbox1.xview, orient="horizontal")
        self.Listbox1.configure(xscrollcommand=self.scroll.set)
        self.scroll.pack(side="bottom")
        self.Listbox1.place(relx=0.15, rely=0.2, relheight=0.427, relwidth=0.7)

        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")

        self.TableName = tk.Label(top)
        self.TableName.place(relx=0.183, rely=0.133, height=21, width=300)
        self.TableName.configure(background="#d9d9d9")
        self.TableName.configure(disabledforeground="#a3a3a3")
        self.TableName.configure(foreground="#000000")
        self.TableName.configure(text='''Table,View Name and It's Attributes description''')
        self.ExecuteQuery()


if __name__ == '__main__':
    vp_start_gui()
